apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: source
      description: The workspace where the Git repository will be cloned.
  params:
    - name: url
      description: The URL of the Git repository to clone.
      type: string
    - name: revision
      description: The branch, tag, or commit to check out.
      type: string
      default: main  # You can set the default branch here.
  steps:
    - name: cleanup-step
      image: alpine
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        # Check if there are any files or folders in the workspace and delete them
        rm -rf helloworld
    - name: git-clone-step
      image: alpine/git
      workingDir: /workspace/source
      script: |
        # Clone the Git repository
        git clone $(params.url)
        cd helloworld
        git checkout $(params.revision)
        # Check out the specified revision
	# Show Commit
	git rev-parse HEAD
    - name: read-readme
      image: alpine
      workingDir: /workspace/source/
      script: |
        #!/bin/sh
        cat helloworld/README.md
